CREATE OR REPLACE PROCEDURE ERRORLOG
is 
BEGIN
	
	INSERT 
		INTO T2 
	SELECT 
		COLA,
		COLB,
		TO_TIMESTAMP('01-JAN-2018 12:00:00.000 AM', 'DD-MON-YYYY HH:MI:SS.FF AM')
	FROM 
		T1 
	LOG ERRORS INTO err$_T2EXCP ('T2_INSERT') REJECT LIMIT UNLIMITED;

	COMMIT;
	
EXCEPTION 
	WHEN OTHERS THEN 
	RAISE;
END ERRORLOG;
/
