SELECT * FROM AGENT_FACT
/
DROP TABLE AGENT_FACT
/
CREATE TABLE AGENT_FACT
AS
SELECT MNTH.MOS AS PAID_MM, AGENT_TYPE, AGENT_SUB_TYPE, AMOUNT
FROM
(SELECT LEVEL AS MOS FROM DUAL CONNECT BY LEVEL < 13) MNTH
LEFT OUTER JOIN
(
SELECT 
TO_CHAR(TO_CHAR(PAID_DATE,'MM'), 'FM00') AS MOS,
CASE AGNT_TYPE
  WHEN 9 THEN 'PPO'
  ELSE 'HMO'
END AS AGENT_TYPE,
CASE AGNT_SUB_TYPE
  WHEN 1 THEN 'SA'
  WHEN 2 THEN 'GA'
  ELSE 'MA'
END AS AGENT_SUB_TYPE,
AMOUNT
FROM 
  (
SELECT 
   ROUND(DBMS_RANDOM.VALUE(1999,2007)) AS COCE_ID,
   --TO_DATE(TRUNC(DBMS_RANDOM.VALUE(2457389,2457389+364)),'J') as PAID_DATE,
   TO_DATE(TRUNC(DBMS_RANDOM.VALUE(2457389,2457389+120)),'J') AS PAID_DATE,
   DBMS_RANDOM.VALUE(9,10) AS AGNT_TYPE,
   ROUND(DBMS_RANDOM.VALUE(1,3)) AS AGNT_SUB_TYPE,
   TRUNC(DBMS_RANDOM.VALUE(10, 100),2) AS AMOUNT   
FROM
  (SELECT LEVEL FROM DUAL CONNECT BY LEVEL < 100)
  )
) COCE
ON COCE.MOS = MNTH.MOS
ORDER BY MNTH.MOS
/
DROP TABLE AGNT_PAID_SUMM
/
SELECT * FROM AGNT_PAID_SUMM
/
CREATE TABLE AGNT_PAID_SUMM
AS
SELECT 
 PAID_MM,
 SUM(HMO_GA_AMOUNT) AS HMO_GA,
 SUM(HMO_SA_AMOUNT) AS HMO_SA,
 SUM(HMO_MA_AMOUNT) AS HMO_MA,
 (SUM(HMO_GA_AMOUNT) + SUM(HMO_SA_AMOUNT) + SUM(HMO_MA_AMOUNT)) AS HMO_TOTAL_AMOUNT,
 SUM(PPO_GA_AMOUNT) AS PPO_GA,
 SUM(PPO_SA_AMOUNT) AS PPO_SA,
 SUM(PPO_MA_AMOUNT) AS PPO_MA,
 (SUM(PPO_GA_AMOUNT) + SUM(PPO_SA_AMOUNT) + SUM(PPO_MA_AMOUNT)) AS PPO_TOTAL_AMOUNT,
 0 AS HMO_AMT_VAR,
 0 AS PPO_AMT_VAR
FROM ( 
SELECT
 PAID_MM,
 HMO_GA_AMOUNT,
 HMO_SA_AMOUNT,
 HMO_MA_AMOUNT,
 PPO_GA_AMOUNT,
 PPO_SA_AMOUNT,
 PPO_MA_AMOUNT
FROM  
  (
SELECT * FROM AGENT_FACT
  ) PIVOT (SUM(AMOUNT) AS AMOUNT FOR (AGENT_TYPE, AGENT_SUB_TYPE) IN (('HMO', 'GA') HMO_GA, ('HMO', 'SA') HMO_SA, ('HMO', 'MA') HMO_MA,
                                                                       ('PPO', 'GA') PPO_GA, ('PPO', 'SA') PPO_SA, ('PPO', 'MA') PPO_MA))
)  
GROUP BY PAID_MM
ORDER BY PAID_MM
/
SELECT 
  PAID_MM, 
  HMO_TOTAL_AMOUNT, 
  PPO_TOTAL_AMOUNT, 
  TRUNC(HMO_AMT_VAR*100, 2) AS HMO_VARIAN,
  TRUNC(PPO_AMT_VAR*100, 2) AS PPO_VARIAN
FROM 
  AGNT_PAID_SUMM
MODEL RETURN UPDATED ROWS
DIMENSION BY (PAID_MM)
MEASURES (HMO_AMT_VAR, HMO_TOTAL_AMOUNT, PPO_AMT_VAR, PPO_TOTAL_AMOUNT)
RULES 
(
HMO_AMT_VAR [PAID_MM] = ((HMO_TOTAL_AMOUNT[CV(PAID_MM)] - HMO_TOTAL_AMOUNT[to_char(CV(PAID_MM)-1,'FM00')])/HMO_TOTAL_AMOUNT[to_char(CV(PAID_MM)-1,'FM00')]),
PPO_AMT_VAR [PAID_MM] = ((PPO_TOTAL_AMOUNT[CV(PAID_MM)] - PPO_TOTAL_AMOUNT[to_char(CV(PAID_MM)-1,'FM00')])/PPO_TOTAL_AMOUNT[to_char(CV(PAID_MM)-1,'FM00')])
)
ORDER BY PAID_MM