DROP TABLE AGENT_FACT
/
CREATE TABLE AGENT_FACT
AS
SELECT MNTH.MOS AS PAID_MM, AGENT_TYPE, AMOUNT
FROM
(SELECT LEVEL AS MOS FROM DUAL CONNECT BY LEVEL < 13) MNTH
LEFT OUTER JOIN
(
SELECT 
TO_CHAR(TO_CHAR(PAID_DATE,'MM'), 'FM00') AS MOS,
CASE AGNT_TYPE
  WHEN 1 THEN 'SA'
  WHEN 2 THEN 'GA'
  ELSE 'MA'
END AS AGENT_TYPE,
AMOUNT
FROM 
  (
SELECT 
   ROUND(DBMS_RANDOM.VALUE(1999,2007)) AS COCE_ID,
   --TO_DATE(TRUNC(DBMS_RANDOM.VALUE(2457389,2457389+364)),'J') as PAID_DATE,
   TO_DATE(TRUNC(DBMS_RANDOM.VALUE(2457389,2457389+120)),'J') AS PAID_DATE,
   ROUND(DBMS_RANDOM.VALUE(1,3)) AS AGNT_TYPE,
   TRUNC(DBMS_RANDOM.VALUE(10, 100),2) AS AMOUNT   
FROM
  (SELECT LEVEL FROM DUAL CONNECT BY LEVEL < 100)
  )
) COCE
ON COCE.MOS = MNTH.MOS
ORDER BY MNTH.MOS
/
SELECT TO_CHAR(TO_DATE('01/01/2016','mm/dd/yyyy'),'J') FROM DUAL;
/
SELECT * FROM AGENT_FACT
/
DROP TABLE AGNT_PAID_SUMM
/
CREATE TABLE AGNT_PAID_SUMM
AS
SELECT 
 PAID_MM,
 SUM(GA_AMOUNT) AS GA,
 SUM(SA_AMOUNT) AS SA,
 SUM(MA_AMOUNT) AS MA,
 (SUM(GA_AMOUNT) + SUM(SA_AMOUNT) + SUM(MA_AMOUNT)) AS TOTAL_AMOUNT,
 0 AS AMT_VAR
FROM ( 
SELECT
 PAID_MM,
 GA_AMOUNT,
 SA_AMOUNT,
 MA_AMOUNT
FROM  
  (
SELECT * FROM AGENT_FACT
  ) PIVOT (SUM(AMOUNT) AS AMOUNT FOR (AGENT_TYPE) IN ('GA' AS GA, 'SA' AS SA, 'MA' AS MA))
)  
GROUP BY PAID_MM
/
SELECT 
  PAID_MM, 
  TOTAL_AMOUNT, 
  TRUNC(AMT_VAR*100, 2) AS VARIAN
FROM 
  AGNT_PAID_SUMM
MODEL RETURN UPDATED ROWS
DIMENSION BY (PAID_MM)
MEASURES (AMT_VAR, TOTAL_AMOUNT)
RULES 
(
AMT_VAR [PAID_MM] = ((TOTAL_AMOUNT[CV(PAID_MM)] - TOTAL_AMOUNT[to_char(CV(PAID_MM)-1,'FM00')])/TOTAL_AMOUNT[to_char(CV(PAID_MM)-1,'FM00')])
)
ORDER BY PAID_MM