whenever sqlerror exit 1;
SET SERVEROUTPUT ON;
CLEAR BUFF
CLEAR COMPUTE
CLEAR BREAKS
CLEAR COLUMNS
/*-----------------------------------------------------------------------------
Name         : 

Revison History :
     1.0 - Cognizant Offshore -  08/01/2017 - Initial Version
-----------------------------------------------------------------------------*/
SET PAGESIZE 50000 EMBEDDED ON
SET ECHO OFF
SET TERMOUT OFF
SET LINESIZE 143
SET FEEDBACK OFF
SET HEADER ON
SET TTITLE ON 
SET UNDERLINE -
SET REPHEADER ON
SET HEADSEP ON
SET SPACE 5
SET HEADING ON

SPOOL '&1'
REPHEADER PAGE LEFT 'PROGRAM NO: QVBLB147 ' CENTER '***  HIP OF GREATER NY ***' - 
RIGHT 'PAGE NO:         1' - 
SKIP 1 COL 126 'RUN DATE: 'TODAY -
SKIP 1 COL 126 'RUN TIME: 'TIME -
SKIP 1 CENTER '-------------------------' -
SKIP 2 CENTER 'E R R O R    R E P O R T' -
SKIP 1 CENTER 'FOR CMS MEDICARE PAYMENT FILE' -
SKIP 1 CENTER 'HCIN H3330   AS OF 'TODAY-
SKIP 1 

COLUMN RUN_TIME NEW_VALUE TIME NOPRINT
COLUMN RUN_DATE NEW_VALUE TODAY NOPRINT
COLUMN CONTRACT HEADING 'MEDICARE CLAIM|NUMBER' 
COLUMN FIRST_PREM HEADING 'PART C|PREMIUMS' JUSTIFY CENTER
COLUMN PMT_DUE_DT HEADING 'PAYMENT|DUE DATE' JUSTIFY CENTER
COLUMN SECOND_PREM HEADING 'PART D|PREMIUMS' JUSTIFY CENTER
COLUMN FEE HEADING 'PART D|PENALTIES' JUSTIFY CENTER
COLUMN TOT_PREM HEADING 'TOTAL|PREMIUM AMT' JUSTIFY CENTER
COLUMN REASON HEADING 'REASON|FOR ERROR' JUSTIFY CENTER

BREAK ON REPORT
COMPUTE SUM LABEL 'TOTAL PREMIUM' OF TOTAL_PREM ON REPORT

SELECT TO_CHAR(SYSDATE, 'MM/DD/YY') AS RUN_DATE, TO_CHAR(SYSDATE, 'HH24:MI:SS') AS RUN_TIME  FROM DUAL;

SELECT 
contract,
pmt_due_dt,
first_prem,
fee,
second_prem,
TOTAL_PREM,
reason
FROM 
PAYMENT_STAGE;

SPOOL OFF;
SET TERMOUT ON
EXIT;
