SELECT 
	HICN_NBR, 
	PYMT_DUE_DT, 
	PART_C_PREM, 
	PART_D_PREM, 
	PART_D_LEP, 
	TOTL_PREM, 
	REASON_DESC,
	TO_CHAR(SYSDATE,'MM/DD/YY') RUN_DATE,
	TO_CHAR(SYSDATE,'HH24:MI:SS') RUN_TIME
FROM EMBT_FCTS_MPWR_EXCP_GEN
UNION ALL
SELECT 
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	TO_CHAR(SYSDATE,'MM/DD/YY') RUN_DATE, 
	TO_CHAR(SYSDATE,'HH24:MI:SS') RUN_TIME 
FROM DUAL;
