WHENEVER SQLERROR EXIT FAILURE
WHENEVER OSERROR EXIT FAILURE
SET SERVEROUTPUT ON;
/*-----------------------------------------------------------------------------
Name         : 

Revison History :
     1.0 - Cognizant Offshore -  08/01/2017 - Initial Version
-----------------------------------------------------------------------------*/
SET PAGESIZE 10000 EMBEDDED ON
SET ECHO OFF
SET TERMOUT OFF
SET LINESIZE 143
SET FEEDBACK OFF
SET HEADER ON
SET TTITLE ON 
SET UNDERLINE -
SET REPHEADER ON
SET HEADSEP ON
SET NUMWIDTH ON
SET LABEL ON
SET SPACE 5
SET HEADING ON
SET BTITLE ON
SET REPFOOTER ON

SPOOL '&1'
COLUMN RUN_DATE NEW_VALUE RDTVAR NOPRINT
COLUMN RUN_TIME NEW_VALUE RTVAR NOPRINT
REPHEADER PAGE LEFT 'PROGRAM NO: QVBLB147 ' CENTER '***  HIP OF GREATER NY ***' - 
RIGHT 'PAGE NO:         1' - 
SKIP 1 COL 126 'RUN DATE: 'RDTVAR - 
SKIP 1 COL 126 'RUN TIME: 'RTVAR -
SKIP 2 CENTER 'E R R O R    R E P O R T' -
SKIP 1 CENTER '-------------------------' -
SKIP 1 CENTER 'FOR CMS MEDICARE PAYMENT FILE' -
SKIP 1 CENTER 'HCIN H3330   AS OF 'RDTVAR-
SKIP 2 
COLUMN MEDCR_CLAIM_NUM HEADING 'MEDICARE|CLAIM NUMBER' JUSTIFY CENTER
COLUMN PMT_DUE_DT HEADING 'PAYMENT|DUE DATE' JUSTIFY CENTER
COLUMN PARTC_PREM HEADING 'PART C|PREMIUMS' JUSTIFY CENTER
COLUMN PARTD_PREM HEADING 'PART D|PREMIUMS' JUSTIFY CENTER
COLUMN PARTD_PENAL HEADING 'PART D|PENALTIES' JUSTIFY CENTER
COLUMN TOT_PREM_AMT HEADING 'TOTAL|PREMIUM AMT' JUSTIFY CENTER
COLUMN RSN_FOR_ERR HEADING 'REASON|FOR ERROR' JUSTIFY CENTER

BREAK ON REPORT  
COMPUTE SUM LABEL TOTAL OF TOT_PREM_AMT ON REPORT
COMPUTE SUM OF TOT_PREM_AMT ON REPORT


SELECT 
TO_CHAR(sysdate, 'DD/MM/YY') AS RUN_DATE,
TO_CHAR(SYSDATE,'HH24:MI:SS') AS RUN_TIME,
MEDCR_CLAIM_NUM,
PMT_DUE_DT,
PARTC_PREM,
PARTD_PREM,
PARTD_PENAL,
TOT_PREM_AMT,
RSN_FOR_ERR FROM FACETS_STAGE.EMBT_FCTS_MPWR_ERR_RPT_STG;


SPOOL OFF;
SET TERMOUT ON
EXIT;